# Generated by Django 2.1.3 on 2018-11-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readcount',
            options={'verbose_name': '浏览计数'},
        ),
    ]
