# Generated by Django 2.1.3 on 2018-11-10 01:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='context',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(default='无主题', max_length=60, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateField(default=datetime.datetime(2018, 11, 10, 9, 55, 32, 488707), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='博主'),
        ),
    ]
