# Generated by Django 2.1.3 on 2018-11-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181110_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(default='2018-11-10,11:20:26', verbose_name='更新时间'),
        ),
    ]
