# Generated by Django 2.1.3 on 2018-11-10 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181110_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 11, 22, 6, 789229), verbose_name='更新时间'),
        ),
    ]
