# Generated by Django 2.1.3 on 2018-11-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181110_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(default='2018-11-10,11:29:17', verbose_name='更新时间'),
        ),
    ]
