# Generated by Django 2.1.3 on 2018-11-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181111_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-update'], 'verbose_name': '博客'},
        ),
    ]
