# Generated by Django 2.1.3 on 2018-11-27 13:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181120_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='context',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=128, null=True),
        ),
    ]
